// <auto-generated />
namespace JobSeeker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewPasswordColumnIsRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewPasswordColumnIsRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202202091124105_NewPasswordColumnIsRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
